// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxowynvpftosrmgeqxks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4b3d5bnZwZnRvc3JtZ2VxeGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTA2MDYsImV4cCI6MjA3MDY4NjYwNn0.LoKolOkI8jheOXEhIqke1aU65CTbNq6CI8RY1tA2uuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});